//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSailing.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tranlations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tranlations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMSailing.App_GlobalResources.Tranlations", typeof(Tranlations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Member.
        /// </summary>
        public static string addMember {
            get {
                return ResourceManager.GetString("addMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string changeLanguage {
            get {
                return ResourceManager.GetString("changeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Member.
        /// </summary>
        public static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Member Added.
        /// </summary>
        public static string createSucess {
            get {
                return ResourceManager.GetString("createSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Sucessful.
        /// </summary>
        public static string deleteSucess {
            get {
                return ResourceManager.GetString("deleteSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Updated.
        /// </summary>
        public static string editSucess {
            get {
                return ResourceManager.GetString("editSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and must match email pattern. ex: foo@outlook.com.
        /// </summary>
        public static string errorEmail {
            get {
                return ResourceManager.GetString("errorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member ID already in use.
        /// </summary>
        public static string errorMemberId {
            get {
                return ResourceManager.GetString("errorMemberId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number must use dash notation. ex 519-748-5220.
        /// </summary>
        public static string errorPhone {
            get {
                return ResourceManager.GetString("errorPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and must match canadian postal code standards. ex :N1N 2K2.
        /// </summary>
        public static string errorPostalCode {
            get {
                return ResourceManager.GetString("errorPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Code is only 2 letters. ex: ON for Ontario.
        /// </summary>
        public static string errorProvinceCode {
            get {
                return ResourceManager.GetString("errorProvinceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Code is not on file, please select correct province code or contact administrator for error.
        /// </summary>
        public static string errorProvinceCodeNOF {
            get {
                return ResourceManager.GetString("errorProvinceCodeNOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string errorRequired {
            get {
                return ResourceManager.GetString("errorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have a last name without first name.
        /// </summary>
        public static string errorSpouseLastName {
            get {
                return ResourceManager.GetString("errorSpouseLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string fullName {
            get {
                return ResourceManager.GetString("fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Phone Number.
        /// </summary>
        public static string homePhone {
            get {
                return ResourceManager.GetString("homePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member ID.
        /// </summary>
        public static string memberId {
            get {
                return ResourceManager.GetString("memberId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string members {
            get {
                return ResourceManager.GetString("members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string postalCode {
            get {
                return ResourceManager.GetString("postalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Code.
        /// </summary>
        public static string provinceCode {
            get {
                return ResourceManager.GetString("provinceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouse First Name.
        /// </summary>
        public static string spouseFirstName {
            get {
                return ResourceManager.GetString("spouseFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouse Last Name.
        /// </summary>
        public static string spouseLastName {
            get {
                return ResourceManager.GetString("spouseLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string street {
            get {
                return ResourceManager.GetString("street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Exempt.
        /// </summary>
        public static string taskExempt {
            get {
                return ResourceManager.GetString("taskExempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Canada Post?.
        /// </summary>
        public static string useCanadaPost {
            get {
                return ResourceManager.GetString("useCanadaPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Joined.
        /// </summary>
        public static string yearJoined {
            get {
                return ResourceManager.GetString("yearJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item?.
        /// </summary>
        public static string youSure {
            get {
                return ResourceManager.GetString("youSure", resourceCulture);
            }
        }
    }
}
